"""followers

Revision ID: 435a11ec3289
Revises: faff7f2be526
Create Date: 2023-08-07 16:55:58.053825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435a11ec3289'
down_revision = 'faff7f2be526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
